language: php

sudo: false

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache/files

matrix:
    include:
        - php: 7.0
          env: SYMFONY_REQUIRE='3.*'
        - php: 7.1
          env: SYMFONY_REQUIRE='4.*'
        # Symfony 5
        - php: 7.2
        - php: 7.3
        - php: 7.4

before_install:
  - composer global require symfony/flex --no-scripts
  - if [ "$SYMFONY_LTS" != "" ]; then composer config extra.symfony.require $SYMFONY_REQUIRE fi

install:
  - composer update $COMPOSER_FLAGS --prefer-dist
  - ./phpunit install

script: ./phpunit
